services:
  users-management-find-all:
    image: ghcr.io/reitansora/users-management-find-all:latest
    container_name: users-management-find-all
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - DB_URL=${DB_URL}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - users-management-find-all
    networks:
      - webnet
    command: ["sh","-c","echo 'Waiting 15s for auth-login to start…' && sleep 15 && echo 'Starting nginx now' && exec nginx -g 'daemon off;'"]

networks:
  webnet:
    driver: bridge
    name: webnet